Refacto contact page
WildCodeSchool/blog-e-boulga-mvc pull request #17
Opened 2024-01-24 18:31 UTC by LuckyShuii

2024-01-24 18:37 UTC, LuckyShuii commented
I messed up again Jesus .. ignore the articles files in this PR they are already present in an other PR

2024-01-25 08:53 UTC, Richarddesnoues requested changes

2024-01-25 08:53 UTC, Richarddesnoues commented on public/assets/js/contact.js
> +let btn_envoie = document.querySelector("#btn_submit")
variable en français ?

2024-01-25 08:53 UTC, Richarddesnoues commented on public/assets/js/contact.js
> +btn_envoie.addEventListener("click", (event) => {
là aussi

2024-01-25 08:53 UTC, Richarddesnoues commented on public/assets/js/contact.js
> +                    if (elementID === "prenom" && valueInput.length < 2) {
FRANCAIS ! !

2024-01-25 08:53 UTC, Richarddesnoues commented on public/assets/js/contact.js
> +                    if (elementID === "nom" && valueInput.length < 2) {
FRANCAIS !!!

2024-01-25 09:03 UTC, LuckyShuii commented on public/assets/js/contact.js
> +btn_envoie.addEventListener("click", (event) => {
changed 👉🏽 next commit

2024-01-25 09:03 UTC, LuckyShuii commented on public/assets/js/contact.js
> +let btn_envoie = document.querySelector("#btn_submit")
changed 👉🏽 next commit

2024-01-25 09:06 UTC, LuckyShuii commented on public/assets/js/contact.js
> +                    if (elementID === "prenom" && valueInput.length < 2) {
changed 👉🏽 next commit

2024-01-25 09:07 UTC, LuckyShuii commented on public/assets/js/contact.js
> +                    if (elementID === "nom" && valueInput.length < 2) {
changed 👉🏽 next commit

2024-01-25 09:10 UTC, Richarddesnoues approved these changes

2024-01-25 10:31 UTC, Benja-san approved these changes

2024-01-25 10:31 UTC, Benja-san commented on src/Controller/ArticleController.php
> +        $article = $articleManager->selectOneById($id);
getArticle now ?

2024-01-25 10:31 UTC, Benja-san commented on src/Controller/ContactController.php
> +    private function validateRequiredFields(array $fields, array &$errors): void
is the & before error relevant ?

2024-01-25 10:34 UTC, merged