header added fonctionnal
WildCodeSchool/blog-e-boulga-mvc pull request #6
Opened 2024-01-23 15:52 UTC by LuckyShuii

2024-01-23 15:58 UTC, Richarddesnoues approved these changes

2024-01-23 16:14 UTC, Benja-san requested changes

2024-01-23 16:14 UTC, Benja-san commented on public/assets/js/header.js
> +    if (!burgerIcone.classList.contains('opened')) {
toggle function

2024-01-23 16:14 UTC, Benja-san commented on public/assets/js/header.js
> +let burgerIcone = document.querySelector("#burger_icon")
Icon * ?

2024-01-23 16:14 UTC, Benja-san commented on public/assets/js/header.js
> +let burgerMenue = document.querySelector("#burger_menue")
Menu * ?

2024-01-23 16:14 UTC, Benja-san commented on src/View/components/_header.html.twig
> +<ul id="burger_menue">
burger_menu * ?

2024-01-23 16:19 UTC, LuckyShuii commented on public/assets/js/header.js
> +let myHeader = document.querySelector("header")
Both variables deleted next commit - they weren't used in the code anyway

2024-01-23 16:21 UTC, LuckyShuii commented on public/assets/js/header.js
> +let myFooter = document.querySelector("footer")
changed into questSelectorAll instead to fix this - next commit

2024-01-23 16:22 UTC, LuckyShuii commented on public/assets/js/header.js
> +let burgerMenue = document.querySelector("#burger_menue")
fixed - next commit

2024-01-23 16:24 UTC, LuckyShuii commented on src/View/components/_header.html.twig
> +<ul id="burger_menue">
fixed - next commit

2024-01-23 22:05 UTC, LuckyShuii commented on public/assets/js/header.js
> +    if (!burgerIcone.classList.contains('opened')) {
done

2024-01-24 08:11 UTC, Benja-san approved these changes

2024-01-24 08:23 UTC, merged