Feature add update article
WildCodeSchool/blog-e-boulga-mvc pull request #75
Opened 2024-02-06 16:45 UTC by Richarddesnoues

2024-02-07 08:14 UTC, LuckyShuii requested changes

2024-02-07 08:14 UTC, LuckyShuii commented on public/assets/images/articles/65c21362ae9339.70709865.png
???

2024-02-07 08:14 UTC, LuckyShuii commented on public/assets/js/admin/updateForm.js
> +console.log(imageUpload+'imageUpload');
debug code to remove

2024-02-07 08:14 UTC, LuckyShuii commented on public/assets/js/admin/updateForm.js
> +   console.log(input.files);
debug code to remove

2024-02-08 08:51 UTC, Benja-san requested changes
Did you think about option picker for article current author, status and category ?

2024-02-08 08:51 UTC, Benja-san commented on src/View/Admin/components/_form_articleUpdate.html.twig
> +>>>>>>> 6641439077193b08b1e5f3e061f6dafbcc003990
git conflict leftovers here

2024-02-08 08:51 UTC, Benja-san commented on src/View/Admin/components/_form_articleUpdate.html.twig
> +=======
git conflict leftovers here

2024-02-08 09:05 UTC, Benja-san approved these changes

2024-02-08 09:08 UTC, LuckyShuii approved these changes

2024-02-08 09:08 UTC, merged